- name: variables from inventory
  host: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course duration is: {{ DURATION }}. Tariner is {{ TRAINER }}"

- name: variables from inventory
  host: Backend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course duration is: {{ DURATION }}. Tariner is {{ TRAINER }}"