- name: vars from preference
  hosts: local
  connection: local
  vars:
    GREEETING: "HELLO from PLAY"
  vars_files:
  - course.yaml
  # vars_prompt:
  # - name: GREEETING
  #   prompt: please enter greeting
  #   private: false
  tasks:
  - name: print the greeting
    # vars:
    #   GREEETING: "Hello from task"
    ansible.builtin.debug:
      msg: "{{ GREEETING }}"